# Generated by Django 5.2.8 on 2025-11-20 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Dealer Name')),
                ('address', models.TextField(verbose_name='Full Address')),
                ('dealer_code', models.CharField(max_length=10, unique=True, verbose_name='Dealer Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Dealer',
                'verbose_name_plural': 'Dealer',
            },
        ),
        migrations.CreateModel(
            name='TestDriveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('car_model', models.CharField(choices=[('', '--- Select Car Model ---'), ('XFORCE HEV', 'XFORCE HEV'), ('Pajero Sport', 'New Pajero Sport'), ('Triton', 'TRITON'), ('Xpander HEV', 'Xpander HEV'), ('Xpander Cross HEV', 'Xpander Cross HEV'), ('Attrage', 'Attrage'), ('Mirage', 'Mirage')], default='', max_length=50)),
                ('preferred_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('confirmation_datetime', models.DateTimeField(blank=True, null=True)),
                ('staff_notes', models.TextField(blank=True, verbose_name='Dealer Notes')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('confirmation_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testdrive_confirmations', to=settings.AUTH_USER_MODEL)),
                ('preferred_dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_drive_requests', to='project.dealer', to_field='dealer_code', verbose_name='Preferred Dealer')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
